# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MCMCirt <- function(X, burnin = 0L, gibbs = 1L, thin = 1L, chains = 2L, verbose = TRUE) {
    .Call('_girt_MCMCirt', PACKAGE = 'girt', X, burnin, gibbs, thin, chains, verbose)
}

MCMCirt_var <- function(Y, alpha, beta, X, burnin = 0L, gibbs = 1L, thin = 1L, chains = 2L, verbose = TRUE, prior_var_gamma = 1, proposal_var = 0.0001) {
    .Call('_girt_MCMCirt_var', PACKAGE = 'girt', Y, alpha, beta, X, burnin, gibbs, thin, chains, verbose, prior_var_gamma, proposal_var)
}

MCMCirtG <- function(Yl, Yc, X, burnin = 0L, gibbs = 1L, thin = 1L, chains = 2L, verbose = TRUE, prior_var_gamma = 100, proposal_var = 0.0001) {
    .Call('_girt_MCMCirtG', PACKAGE = 'girt', Yl, Yc, X, burnin, gibbs, thin, chains, verbose, prior_var_gamma, proposal_var)
}

MCMCirtG2 <- function(Yl, Yc, X, burnin = 0L, gibbs = 1L, thin = 1L, chains = 2L, verbose = TRUE, prior_var_gamma = 100, proposal_var = 0.0001) {
    .Call('_girt_MCMCirtG2', PACKAGE = 'girt', Yl, Yc, X, burnin, gibbs, thin, chains, verbose, prior_var_gamma, proposal_var)
}

MCMCirtG3 <- function(Yl, Yc, X, burnin = 0L, gibbs = 1L, thin = 1L, chains = 2L, verbose = TRUE, prior_var_gamma = 100, proposal_var = 0.0001) {
    .Call('_girt_MCMCirtG3', PACKAGE = 'girt', Yl, Yc, X, burnin, gibbs, thin, chains, verbose, prior_var_gamma, proposal_var)
}

gamma_conditional <- function(Y, X, theta, gamma, prior_var_gamma, alpha, beta, J, N, K) {
    .Call('_girt_gamma_conditional', PACKAGE = 'girt', Y, X, theta, gamma, prior_var_gamma, alpha, beta, J, N, K)
}

update_gamma <- function(Y, X, thetal, gamma, prior_var_gamma, proposal_var, alpha, beta, J, N, K, a) {
    invisible(.Call('_girt_update_gamma', PACKAGE = 'girt', Y, X, thetal, gamma, prior_var_gamma, proposal_var, alpha, beta, J, N, K, a))
}

mvrnormArma <- function(n, mu, sigma) {
    .Call('_girt_mvrnormArma', PACKAGE = 'girt', n, mu, sigma)
}

norm_rs <- function(a, b) {
    .Call('_girt_norm_rs', PACKAGE = 'girt', a, b)
}

half_norm_rs <- function(a, b) {
    .Call('_girt_half_norm_rs', PACKAGE = 'girt', a, b)
}

unif_rs <- function(a, b) {
    .Call('_girt_unif_rs', PACKAGE = 'girt', a, b)
}

exp_rs <- function(a, b) {
    .Call('_girt_exp_rs', PACKAGE = 'girt', a, b)
}

rnorm_trunc <- function(mu, sigma, lower, upper) {
    .Call('_girt_rnorm_trunc', PACKAGE = 'girt', mu, sigma, lower, upper)
}

